name: tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clojure deps cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 'latest'

      - name: Tools Versions
        run: |
          echo "java -version"
          java -version
          echo "clojure --version"
          clojure --version

      - name: Run tests
        run: clojure -M:test
